export const SET_PERSIST= 'persist/REHYDRATE';

export const TOKEN_FETCH = 'TOKEN_FETCH';
export const TOKEN_FETCH_FAIL = 'TOKEN_FETCH_FAIL';
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS';
export const TOKEN_RESET = 'TOKEN_RESET';

export const LOGGEDINMODEL_FETCH = 'LOGGEDINMODEL_FETCH';
export const LOGGEDINMODEL_FETCH_FAIL = 'LOGGEDINMODEL_FETCH_FAIL';
export const LOGGEDINMODEL_SUCCESS = 'LOGGEDINMODEL_SUCCESS';

export const HORIZONTALDEPARTMENTLIST_FETCH = 'HORIZONTALDEPARTMENTLIST_FETCH';
export const HORIZONTALDEPARTMENTLIST_FETCH_FAIL = 'HORIZONTALDEPARTMENTLIST_FETCH_FAIL';
export const HORIZONTALDEPARTMENTLIST_SUCCESS = 'HORIZONTALDEPARTMENTLIST_SUCCESS';

export const HORIZONTALSPECIALPRODUCTLIST_FETCH = 'HORIZONTALSPECIALPRODUCTLIST_FETCH';
export const HORIZONTALSPECIALPRODUCTLIST_FETCH_FAIL = 'HORIZONTALSPECIALPRODUCTLIST_FETCH_FAIL';
export const HORIZONTALSPECIALPRODUCTLIST_SUCCESS = 'HORIZONTALSPECIALPRODUCTLIST_SUCCESS';

export const HORIZONTALWORKPRODUCTLIST_FETCH = 'HORIZONTALWORKPRODUCTLIST_FETCH';
export const HORIZONTALWORKPRODUCTLIST_FETCH_FAIL = 'HORIZONTALWORKPRODUCTLIST_FETCH_FAIL';
export const HORIZONTALWORKPRODUCTLIST_SUCCESS = 'HORIZONTALWORKPRODUCTLIST_SUCCESS';

export const AUTOCOMPLETECITY_FETCH = 'AUTOCOMPLETECITY_FETCH';
export const AUTOCOMPLETECITY_SUCCESS = 'AUTOCOMPLETECITY_SUCCESS';
export const AUTOCOMPLETECITY_FETCH_FAIL = 'AUTOCOMPLETECITY_FETCH_FAIL';
export const AUTOCOMPLETECITY_RESET = 'AUTOCOMPLETECITY_RESET';

export const COMMON_SET_CITY = 'COMMON_SET_CITY';
export const COMMON_SET_ISLOGGEDIN = 'COMMON_SET_ISLOGGEDIN';
export const COMMON_SET_BASKETBADGENUMBER = 'COMMON_SET_BASKETBADGENUMBER';


export const HOMEPLANS_FETCH = 'HOMEPLANS_FETCH';
export const HOMEPLANS_FETCH_FAIL = 'HOMEPLANS_FETCH_FAIL';
export const HOMEPLANS_SUCCESS = 'HOMEPLANS_SUCCESS';


